/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentRidesRouteImport } from './routes/student.rides'
import { Route as StudentNotesRouteImport } from './routes/student.notes'
import { Route as StudentMedicalRouteImport } from './routes/student.medical'
import { Route as StudentFoodRouteImport } from './routes/student.food'
import { Route as FacultyUploadRouteImport } from './routes/faculty.upload'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentRidesRoute = StudentRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotesRoute = StudentNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMedicalRoute = StudentMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFoodRoute = StudentFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyUploadRoute = FacultyUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => FacultyRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/faculty/upload': typeof FacultyUploadRoute
  '/student/food': typeof StudentFoodRoute
  '/student/medical': typeof StudentMedicalRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/rides': typeof StudentRidesRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/faculty/upload': typeof FacultyUploadRoute
  '/student/food': typeof StudentFoodRoute
  '/student/medical': typeof StudentMedicalRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/rides': typeof StudentRidesRoute
  '/admin': typeof AdminIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/faculty/upload': typeof FacultyUploadRoute
  '/student/food': typeof StudentFoodRoute
  '/student/medical': typeof StudentMedicalRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/rides': typeof StudentRidesRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faculty'
    | '/login'
    | '/notifications'
    | '/register'
    | '/student'
    | '/admin/orders'
    | '/admin/users'
    | '/faculty/upload'
    | '/student/food'
    | '/student/medical'
    | '/student/notes'
    | '/student/rides'
    | '/admin/'
    | '/faculty/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/register'
    | '/admin/orders'
    | '/admin/users'
    | '/faculty/upload'
    | '/student/food'
    | '/student/medical'
    | '/student/notes'
    | '/student/rides'
    | '/admin'
    | '/faculty'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faculty'
    | '/login'
    | '/notifications'
    | '/register'
    | '/student'
    | '/admin/orders'
    | '/admin/users'
    | '/faculty/upload'
    | '/student/food'
    | '/student/medical'
    | '/student/notes'
    | '/student/rides'
    | '/admin/'
    | '/faculty/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/rides': {
      id: '/student/rides'
      path: '/rides'
      fullPath: '/student/rides'
      preLoaderRoute: typeof StudentRidesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notes': {
      id: '/student/notes'
      path: '/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof StudentNotesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/medical': {
      id: '/student/medical'
      path: '/medical'
      fullPath: '/student/medical'
      preLoaderRoute: typeof StudentMedicalRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/food': {
      id: '/student/food'
      path: '/food'
      fullPath: '/student/food'
      preLoaderRoute: typeof StudentFoodRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/upload': {
      id: '/faculty/upload'
      path: '/upload'
      fullPath: '/faculty/upload'
      preLoaderRoute: typeof FacultyUploadRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyRouteChildren {
  FacultyUploadRoute: typeof FacultyUploadRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyUploadRoute: FacultyUploadRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentFoodRoute: typeof StudentFoodRoute
  StudentMedicalRoute: typeof StudentMedicalRoute
  StudentNotesRoute: typeof StudentNotesRoute
  StudentRidesRoute: typeof StudentRidesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentFoodRoute: StudentFoodRoute,
  StudentMedicalRoute: StudentMedicalRoute,
  StudentNotesRoute: StudentNotesRoute,
  StudentRidesRoute: StudentRidesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
